# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88670bedd1f982ad7d0e04ab13d4f8830fbea698ae36430de436a43a5cc654b2b555807760281235a9593f302cc365744ef3c32264c570740a77a6233bfc5d23

test:
  secret_key_base: e32801390c5df861fbf39dbe54512655ad233941d6c4c2be9cb7db8f10d427df8bda8f97eb309ea07610acd67ca0c55dd1700a2c999c3b35ef56203bdb02b467

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
